kind: pipeline
name: default

workspace:
   base: /go
   path: src/github.com/fanux/fist/

steps:
- name: build-fist
  image: golang:1.10.8
  commands:
     - go get -v
     - go get -u golang.org/x/lint/golint
     - golint  -set_exit_status ./...
     - go build -o fist

- name: publish-fist
  image: plugins/docker
  settings:
    repo: lameleg/fist
    tags: ${DRONE_TAG=latest}
    username:
      from_secret: docker-hub-user
    dockerfile: deploy/Dockerfile
    password:
      from_secret: docker-hub-pass

- name: deploy-auth
  image: lachlanevenson/k8s-kubectl
  commands:
  - mkdir ~/.kube
  - cp deploy/config ~/.kube/config
  - cd auth/deploy
  - kubectl delete -f auth.yaml  || true
  - kubectl delete -f secret.yaml  || true
  - sleep 15
  - kubectl create -f secret.yaml  || true
  - kubectl create -f auth.yaml  || true

- name: deploy-terminal
  image: lachlanevenson/k8s-kubectl
  commands:
  - mkdir ~/.kube
  - cp deploy/config ~/.kube/config
  - kubectl delete -f terminal/deploy/deploy.yaml  || true
  - sleep 15
  - kubectl create -f  terminal/deploy/deploy.yaml || true
